CC      := powerpc-eabi-gcc
CXX     := powerpc-eabi-g++
CFLAGS  := -g -O3 -flto -fuse-linker-plugin -Wall
LDFLAGS := -O3 -flto -fuse-linker-plugin
TARGET  := myapp
SRCS    := $(wildcard wii/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
# Make requires <tab> to separate 
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET)
