name: Wii-ppc
on:
  push:
    branches:
    - fast
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install OpenGX
      run: |
        cd .
        git clone https://github.com/devkitPro/opengx.git
        cd opengx
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" ..
        make && sudo -E PATH=$PATH make install 
    - name: Install FreeGLUT
      run: |
        cd .
        git clone https://github.com/freeglut/freeglut.git
        cd freeglut
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" -DFREEGLUT_BUILD_DEMOS=OFF ..
        make && sudo -E PATH=$PATH make install 
    - name: Compile
      run: |
        make -f Makefile.ppc3lib
    - name: Create tarball
      run: |
          tar -cvf libretro_wii.tgz libretro_wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./libretro_wii.tgz
