name: Wii-ppc-ra-1191
on:
  push:
    branches:
    - fast
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-devkitpro:latest
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install RetroArch
      run: |
        cd .
        git clone https://github.com/libretro/RetroArch.git retroarch --recursive
    - name: Install OpenGX
      run: |
        cd .
        git clone https://github.com/devkitPro/opengx.git
        cd opengx
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" ..
        make && sudo -E PATH=$PATH make install 
    - name: Install FreeGLUT
      run: |
        cd .
        git clone https://github.com/freeglut/freeglut.git
        cd freeglut
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" -DFREEGLUT_BUILD_DEMOS=OFF ..
        make && sudo -E PATH=$PATH make install 
    - name: Compile libretro_wii.a
      run: |
        make -f Makefile.ppc4lib
        cp ./libretro_wii.a ./retroarch
    - name: Compile RA Frontend
      run: |
        cd retroarch
        make -f Makefile.wii.salamander EXTERNAL_LIBOGC=1 GX_PTHREAD_LEGACY=0
        make -f Makefile.griffin platform=wii EXTERNAL_LIBOGC=1 GX_PTHREAD_LEGACY=0
    - name: Create tarball
      run: |
          tar -cvf libretro_wii.a.tgz libretro_wii.a
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Artifact
        path: |
          ./libretro_wii.a.tgz
